export const SET_LOADER = "SET_LOADER";
export const MY_API_ERROR = "MY_API_ERROR";
export const OPEN_IMAGE_SHOW_MODAL = "OPEN_IMAGE_SHOW_MODAL";
export const SET_TAB_HEADER_STATE = "SET_TAB_HEADER_STATE";
export const SET_TAB_SPECIAL_PRODUCT_STATE = "SET_TAB_SPECIAL_PRODUCT_STATE";

export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const SET_ALL_CATEGORY = "SET_ALL_CATEGORY";

export const GET_ALL_SUB_CATEGORY = "GET_ALL_SUB_CATEGORY";
export const SET_ALL_SUB_CATEGORY = "SET_ALL_SUB_CATEGORY";

export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const SET_ALL_PRODUCT = "SET_ALL_PRODUCT";

export const GET_PRODUCT_VIA_PAGINATION = "GET_PRODUCT_VIA_PAGINATION";

export const GET_SORT_VALUE = "GET_SORT_VALUE";
export const SET_SORT_VALUE = "SET_SORT_VALUE";

export const GET_FILTER_PRODUCT = "GET_SORT_VALUE";
export const SET_FILTER_PRODUCT = "SET_SORT_VALUE";